/* automatically generated by rust-bindgen */


#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
pub type size_t = usize;
pub type wchar_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct div_t {
    pub quot: ::std::os::raw::c_int,
    pub rem: ::std::os::raw::c_int,
}
impl ::std::default::Default for div_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct ldiv_t {
    pub quot: ::std::os::raw::c_long,
    pub rem: ::std::os::raw::c_long,
}
impl ::std::default::Default for ldiv_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct lldiv_t {
    pub quot: ::std::os::raw::c_longlong,
    pub rem: ::std::os::raw::c_longlong,
}
impl ::std::default::Default for lldiv_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type __u_char = ::std::os::raw::c_uchar;
pub type __u_short = ::std::os::raw::c_ushort;
pub type __u_int = ::std::os::raw::c_uint;
pub type __u_long = ::std::os::raw::c_ulong;
pub type __int8_t = ::std::os::raw::c_char;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __quad_t = ::std::os::raw::c_long;
pub type __u_quad_t = ::std::os::raw::c_ulong;
pub type __dev_t = ::std::os::raw::c_ulong;
pub type __uid_t = ::std::os::raw::c_uint;
pub type __gid_t = ::std::os::raw::c_uint;
pub type __ino_t = ::std::os::raw::c_ulong;
pub type __ino64_t = ::std::os::raw::c_ulong;
pub type __mode_t = ::std::os::raw::c_uint;
pub type __nlink_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __pid_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct __fsid_t {
    pub __val: [::std::os::raw::c_int; 2usize],
}
impl ::std::default::Default for __fsid_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type __clock_t = ::std::os::raw::c_long;
pub type __rlim_t = ::std::os::raw::c_ulong;
pub type __rlim64_t = ::std::os::raw::c_ulong;
pub type __id_t = ::std::os::raw::c_uint;
pub type __time_t = ::std::os::raw::c_long;
pub type __useconds_t = ::std::os::raw::c_uint;
pub type __suseconds_t = ::std::os::raw::c_long;
pub type __daddr_t = ::std::os::raw::c_int;
pub type __key_t = ::std::os::raw::c_int;
pub type __clockid_t = ::std::os::raw::c_int;
pub type __timer_t = *mut ::std::os::raw::c_void;
pub type __blksize_t = ::std::os::raw::c_long;
pub type __blkcnt_t = ::std::os::raw::c_long;
pub type __blkcnt64_t = ::std::os::raw::c_long;
pub type __fsblkcnt_t = ::std::os::raw::c_ulong;
pub type __fsblkcnt64_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt64_t = ::std::os::raw::c_ulong;
pub type __fsword_t = ::std::os::raw::c_long;
pub type __ssize_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
pub type __syscall_ulong_t = ::std::os::raw::c_ulong;
pub type __loff_t = __off64_t;
pub type __qaddr_t = *mut __quad_t;
pub type __caddr_t = *mut ::std::os::raw::c_char;
pub type __intptr_t = ::std::os::raw::c_long;
pub type __socklen_t = ::std::os::raw::c_uint;
pub type u_char = __u_char;
pub type u_short = __u_short;
pub type u_int = __u_int;
pub type u_long = __u_long;
pub type quad_t = __quad_t;
pub type u_quad_t = __u_quad_t;
pub type fsid_t = __fsid_t;
pub type loff_t = __loff_t;
pub type ino_t = __ino_t;
pub type dev_t = __dev_t;
pub type gid_t = __gid_t;
pub type mode_t = __mode_t;
pub type nlink_t = __nlink_t;
pub type uid_t = __uid_t;
pub type off_t = __off_t;
pub type pid_t = __pid_t;
pub type id_t = __id_t;
pub type ssize_t = isize;
pub type daddr_t = __daddr_t;
pub type caddr_t = __caddr_t;
pub type key_t = __key_t;
pub type clock_t = __clock_t;
pub type time_t = __time_t;
pub type clockid_t = __clockid_t;
pub type timer_t = __timer_t;
pub type ulong = ::std::os::raw::c_ulong;
pub type ushort = ::std::os::raw::c_ushort;
pub type uint_ = ::std::os::raw::c_uint;
pub type int8_t = i8;
pub type int16_t = i16;
pub type int32_t = i32;
pub type int64_t = i64;
pub type u_int8_t = ::std::os::raw::c_uchar;
pub type u_int16_t = ::std::os::raw::c_ushort;
pub type u_int32_t = ::std::os::raw::c_uint;
pub type u_int64_t = ::std::os::raw::c_ulong;
pub type register_t = ::std::os::raw::c_long;
pub type __sig_atomic_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct __sigset_t {
    pub __val: [::std::os::raw::c_ulong; 16usize],
}
impl ::std::default::Default for __sigset_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type sigset_t = __sigset_t;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct timespec {
    pub tv_sec: __time_t,
    pub tv_nsec: __syscall_slong_t,
}
impl ::std::default::Default for timespec {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct timeval {
    pub tv_sec: __time_t,
    pub tv_usec: __suseconds_t,
}
impl ::std::default::Default for timeval {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type suseconds_t = __suseconds_t;
pub type __fd_mask = ::std::os::raw::c_long;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct fd_set {
    pub __fds_bits: [__fd_mask; 16usize],
}
impl ::std::default::Default for fd_set {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type fd_mask = __fd_mask;
pub type blksize_t = __blksize_t;
pub type blkcnt_t = __blkcnt_t;
pub type fsblkcnt_t = __fsblkcnt_t;
pub type fsfilcnt_t = __fsfilcnt_t;
pub type pthread_t = ::std::os::raw::c_ulong;
#[repr(C)]
#[derive(Copy)]
pub struct pthread_attr_t {
    pub _bindgen_data_: [u64; 7usize],
}
impl pthread_attr_t {
    pub unsafe fn __size(&mut self)
     -> *mut [::std::os::raw::c_char; 56usize] {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __align(&mut self) -> *mut ::std::os::raw::c_long {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
}
impl ::std::clone::Clone for pthread_attr_t {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for pthread_attr_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct __pthread_internal_list {
    pub __prev: *mut __pthread_internal_list,
    pub __next: *mut __pthread_internal_list,
}
impl ::std::default::Default for __pthread_internal_list {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type __pthread_list_t = __pthread_internal_list;
#[repr(C)]
#[derive(Copy)]
pub struct pthread_mutex_t {
    pub _bindgen_data_: [u64; 5usize],
}
impl pthread_mutex_t {
    pub unsafe fn __data(&mut self) -> *mut __pthread_mutex_s {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __size(&mut self)
     -> *mut [::std::os::raw::c_char; 40usize] {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __align(&mut self) -> *mut ::std::os::raw::c_long {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
}
impl ::std::clone::Clone for pthread_mutex_t {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for pthread_mutex_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct __pthread_mutex_s {
    pub __lock: ::std::os::raw::c_int,
    pub __count: ::std::os::raw::c_uint,
    pub __owner: ::std::os::raw::c_int,
    pub __nusers: ::std::os::raw::c_uint,
    pub __kind: ::std::os::raw::c_int,
    pub __spins: ::std::os::raw::c_short,
    pub __elision: ::std::os::raw::c_short,
    pub __list: __pthread_list_t,
}
impl ::std::default::Default for __pthread_mutex_s {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct pthread_mutexattr_t {
    pub _bindgen_data_: [u32; 1usize],
}
impl pthread_mutexattr_t {
    pub unsafe fn __size(&mut self) -> *mut [::std::os::raw::c_char; 4usize] {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __align(&mut self) -> *mut ::std::os::raw::c_int {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
}
impl ::std::default::Default for pthread_mutexattr_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy)]
pub struct pthread_cond_t {
    pub _bindgen_data_: [u64; 6usize],
}
impl pthread_cond_t {
    pub unsafe fn __data(&mut self) -> *mut Struct_Unnamed1 {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __size(&mut self)
     -> *mut [::std::os::raw::c_char; 48usize] {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __align(&mut self) -> *mut ::std::os::raw::c_longlong {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
}
impl ::std::clone::Clone for pthread_cond_t {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for pthread_cond_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct Struct_Unnamed1 {
    pub __lock: ::std::os::raw::c_int,
    pub __futex: ::std::os::raw::c_uint,
    pub __total_seq: ::std::os::raw::c_ulonglong,
    pub __wakeup_seq: ::std::os::raw::c_ulonglong,
    pub __woken_seq: ::std::os::raw::c_ulonglong,
    pub __mutex: *mut ::std::os::raw::c_void,
    pub __nwaiters: ::std::os::raw::c_uint,
    pub __broadcast_seq: ::std::os::raw::c_uint,
}
impl ::std::default::Default for Struct_Unnamed1 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct pthread_condattr_t {
    pub _bindgen_data_: [u32; 1usize],
}
impl pthread_condattr_t {
    pub unsafe fn __size(&mut self) -> *mut [::std::os::raw::c_char; 4usize] {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __align(&mut self) -> *mut ::std::os::raw::c_int {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
}
impl ::std::default::Default for pthread_condattr_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type pthread_key_t = ::std::os::raw::c_uint;
pub type pthread_once_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy)]
pub struct pthread_rwlock_t {
    pub _bindgen_data_: [u64; 7usize],
}
impl pthread_rwlock_t {
    pub unsafe fn __data(&mut self) -> *mut Struct_Unnamed2 {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __size(&mut self)
     -> *mut [::std::os::raw::c_char; 56usize] {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __align(&mut self) -> *mut ::std::os::raw::c_long {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
}
impl ::std::clone::Clone for pthread_rwlock_t {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for pthread_rwlock_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct Struct_Unnamed2 {
    pub __lock: ::std::os::raw::c_int,
    pub __nr_readers: ::std::os::raw::c_uint,
    pub __readers_wakeup: ::std::os::raw::c_uint,
    pub __writer_wakeup: ::std::os::raw::c_uint,
    pub __nr_readers_queued: ::std::os::raw::c_uint,
    pub __nr_writers_queued: ::std::os::raw::c_uint,
    pub __writer: ::std::os::raw::c_int,
    pub __shared: ::std::os::raw::c_int,
    pub __rwelision: ::std::os::raw::c_char,
    pub __pad1: [::std::os::raw::c_uchar; 7usize],
    pub __pad2: ::std::os::raw::c_ulong,
    pub __flags: ::std::os::raw::c_uint,
}
impl ::std::default::Default for Struct_Unnamed2 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct pthread_rwlockattr_t {
    pub _bindgen_data_: [u64; 1usize],
}
impl pthread_rwlockattr_t {
    pub unsafe fn __size(&mut self) -> *mut [::std::os::raw::c_char; 8usize] {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __align(&mut self) -> *mut ::std::os::raw::c_long {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
}
impl ::std::default::Default for pthread_rwlockattr_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type pthread_spinlock_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct pthread_barrier_t {
    pub _bindgen_data_: [u64; 4usize],
}
impl pthread_barrier_t {
    pub unsafe fn __size(&mut self)
     -> *mut [::std::os::raw::c_char; 32usize] {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __align(&mut self) -> *mut ::std::os::raw::c_long {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
}
impl ::std::default::Default for pthread_barrier_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct pthread_barrierattr_t {
    pub _bindgen_data_: [u32; 1usize],
}
impl pthread_barrierattr_t {
    pub unsafe fn __size(&mut self) -> *mut [::std::os::raw::c_char; 4usize] {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn __align(&mut self) -> *mut ::std::os::raw::c_int {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
}
impl ::std::default::Default for pthread_barrierattr_t {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct random_data {
    pub fptr: *mut int32_t,
    pub rptr: *mut int32_t,
    pub state: *mut int32_t,
    pub rand_type: ::std::os::raw::c_int,
    pub rand_deg: ::std::os::raw::c_int,
    pub rand_sep: ::std::os::raw::c_int,
    pub end_ptr: *mut int32_t,
}
impl ::std::default::Default for random_data {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct drand48_data {
    pub __x: [::std::os::raw::c_ushort; 3usize],
    pub __old_x: [::std::os::raw::c_ushort; 3usize],
    pub __c: ::std::os::raw::c_ushort,
    pub __init: ::std::os::raw::c_ushort,
    pub __a: ::std::os::raw::c_ulonglong,
}
impl ::std::default::Default for drand48_data {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type __compar_fn_t =
    ::std::option::Option<unsafe extern "C" fn(arg1:
                                                   *const ::std::os::raw::c_void,
                                               arg2:
                                                   *const ::std::os::raw::c_void)
                              -> ::std::os::raw::c_int>;
pub type uint8_t = u8;
pub type uint16_t = u16;
pub type uint32_t = u32;
pub type uint64_t = u64;
pub type int_least8_t = ::std::os::raw::c_char;
pub type int_least16_t = ::std::os::raw::c_short;
pub type int_least32_t = ::std::os::raw::c_int;
pub type int_least64_t = ::std::os::raw::c_long;
pub type uint_least8_t = ::std::os::raw::c_uchar;
pub type uint_least16_t = ::std::os::raw::c_ushort;
pub type uint_least32_t = ::std::os::raw::c_uint;
pub type uint_least64_t = ::std::os::raw::c_ulong;
pub type int_fast8_t = ::std::os::raw::c_char;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intptr_t = isize;
pub type uintptr_t = usize;
pub type intmax_t = ::std::os::raw::c_long;
pub type uintmax_t = ::std::os::raw::c_ulong;
pub type va_list = __builtin_va_list;
pub type __gnuc_va_list = __builtin_va_list;
pub enum udev { }
pub enum udev_list_entry { }
pub enum udev_device { }
pub enum udev_monitor { }
pub enum udev_enumerate { }
pub enum udev_queue { }
pub enum udev_hwdb { }
pub enum libinput { }
pub enum libinput_device { }
pub enum libinput_device_group { }
pub enum libinput_seat { }
pub enum libinput_tablet_tool { }
pub enum libinput_event { }
pub enum libinput_event_device_notify { }
pub enum libinput_event_keyboard { }
pub enum libinput_event_pointer { }
pub enum libinput_event_touch { }
pub enum libinput_event_tablet_tool { }
pub enum libinput_event_tablet_pad { }
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_log_priority {
    LIBINPUT_LOG_PRIORITY_DEBUG = 10,
    LIBINPUT_LOG_PRIORITY_INFO = 20,
    LIBINPUT_LOG_PRIORITY_ERROR = 30,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_device_capability {
    LIBINPUT_DEVICE_CAP_KEYBOARD = 0,
    LIBINPUT_DEVICE_CAP_POINTER = 1,
    LIBINPUT_DEVICE_CAP_TOUCH = 2,
    LIBINPUT_DEVICE_CAP_TABLET_TOOL = 3,
    LIBINPUT_DEVICE_CAP_TABLET_PAD = 4,
    LIBINPUT_DEVICE_CAP_GESTURE = 5,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_key_state {
    LIBINPUT_KEY_STATE_RELEASED = 0,
    LIBINPUT_KEY_STATE_PRESSED = 1,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_led {
    LIBINPUT_LED_NUM_LOCK = 1,
    LIBINPUT_LED_CAPS_LOCK = 2,
    LIBINPUT_LED_SCROLL_LOCK = 4,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_button_state {
    LIBINPUT_BUTTON_STATE_RELEASED = 0,
    LIBINPUT_BUTTON_STATE_PRESSED = 1,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_pointer_axis {
    LIBINPUT_POINTER_AXIS_SCROLL_VERTICAL = 0,
    LIBINPUT_POINTER_AXIS_SCROLL_HORIZONTAL = 1,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_pointer_axis_source {
    LIBINPUT_POINTER_AXIS_SOURCE_WHEEL = 1,
    LIBINPUT_POINTER_AXIS_SOURCE_FINGER = 2,
    LIBINPUT_POINTER_AXIS_SOURCE_CONTINUOUS = 3,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_tablet_pad_ring_axis_source {
    LIBINPUT_TABLET_PAD_RING_SOURCE_UNKNOWN = 1,
    LIBINPUT_TABLET_PAD_RING_SOURCE_FINGER = 2,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_tablet_pad_strip_axis_source {
    LIBINPUT_TABLET_PAD_STRIP_SOURCE_UNKNOWN = 1,
    LIBINPUT_TABLET_PAD_STRIP_SOURCE_FINGER = 2,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_tablet_tool_type {
    LIBINPUT_TABLET_TOOL_TYPE_PEN = 1,
    LIBINPUT_TABLET_TOOL_TYPE_ERASER = 2,
    LIBINPUT_TABLET_TOOL_TYPE_BRUSH = 3,
    LIBINPUT_TABLET_TOOL_TYPE_PENCIL = 4,
    LIBINPUT_TABLET_TOOL_TYPE_AIRBRUSH = 5,
    LIBINPUT_TABLET_TOOL_TYPE_MOUSE = 6,
    LIBINPUT_TABLET_TOOL_TYPE_LENS = 7,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_tablet_tool_proximity_state {
    LIBINPUT_TABLET_TOOL_PROXIMITY_STATE_OUT = 0,
    LIBINPUT_TABLET_TOOL_PROXIMITY_STATE_IN = 1,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_tablet_tool_tip_state {
    LIBINPUT_TABLET_TOOL_TIP_UP = 0,
    LIBINPUT_TABLET_TOOL_TIP_DOWN = 1,
}
pub enum libinput_tablet_pad_mode_group { }
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_event_type {
    LIBINPUT_EVENT_NONE = 0,
    LIBINPUT_EVENT_DEVICE_ADDED = 1,
    LIBINPUT_EVENT_DEVICE_REMOVED = 2,
    LIBINPUT_EVENT_KEYBOARD_KEY = 300,
    LIBINPUT_EVENT_POINTER_MOTION = 400,
    LIBINPUT_EVENT_POINTER_MOTION_ABSOLUTE = 401,
    LIBINPUT_EVENT_POINTER_BUTTON = 402,
    LIBINPUT_EVENT_POINTER_AXIS = 403,
    LIBINPUT_EVENT_TOUCH_DOWN = 500,
    LIBINPUT_EVENT_TOUCH_UP = 501,
    LIBINPUT_EVENT_TOUCH_MOTION = 502,
    LIBINPUT_EVENT_TOUCH_CANCEL = 503,
    LIBINPUT_EVENT_TOUCH_FRAME = 504,
    LIBINPUT_EVENT_TABLET_TOOL_AXIS = 600,
    LIBINPUT_EVENT_TABLET_TOOL_PROXIMITY = 601,
    LIBINPUT_EVENT_TABLET_TOOL_TIP = 602,
    LIBINPUT_EVENT_TABLET_TOOL_BUTTON = 603,
    LIBINPUT_EVENT_TABLET_PAD_BUTTON = 700,
    LIBINPUT_EVENT_TABLET_PAD_RING = 701,
    LIBINPUT_EVENT_TABLET_PAD_STRIP = 702,
    LIBINPUT_EVENT_GESTURE_SWIPE_BEGIN = 800,
    LIBINPUT_EVENT_GESTURE_SWIPE_UPDATE = 801,
    LIBINPUT_EVENT_GESTURE_SWIPE_END = 802,
    LIBINPUT_EVENT_GESTURE_PINCH_BEGIN = 803,
    LIBINPUT_EVENT_GESTURE_PINCH_UPDATE = 804,
    LIBINPUT_EVENT_GESTURE_PINCH_END = 805,
}
pub enum libinput_event_gesture { }
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct libinput_interface {
    pub open_restricted: ::std::option::Option<fn(path:
                                                                        *const ::std::os::raw::c_char,
                                                                    flags:
                                                                        ::std::os::raw::c_int,
                                                                    user_data:
                                                                        *mut ::std::os::raw::c_void)
                                                   -> ::std::os::raw::c_int>,
    pub close_restricted: ::std::option::Option<fn(fd:
                                                                         ::std::os::raw::c_int,
                                                                     user_data:
                                                                         *mut ::std::os::raw::c_void)>,
}
impl ::std::default::Default for libinput_interface {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type libinput_log_handler =
    ::std::option::Option<unsafe extern "C" fn(libinput: *mut libinput,
                                               priority:
                                                   libinput_log_priority,
                                               format:
                                                   *const ::std::os::raw::c_char,
                                               args: va_list)>;
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_config_status {
    LIBINPUT_CONFIG_STATUS_SUCCESS = 0,
    LIBINPUT_CONFIG_STATUS_UNSUPPORTED = 1,
    LIBINPUT_CONFIG_STATUS_INVALID = 2,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_config_tap_state {
    LIBINPUT_CONFIG_TAP_DISABLED = 0,
    LIBINPUT_CONFIG_TAP_ENABLED = 1,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_config_tap_button_map {
    LIBINPUT_CONFIG_TAP_MAP_LRM = 0,
    LIBINPUT_CONFIG_TAP_MAP_LMR = 1,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_config_drag_state {
    LIBINPUT_CONFIG_DRAG_DISABLED = 0,
    LIBINPUT_CONFIG_DRAG_ENABLED = 1,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_config_drag_lock_state {
    LIBINPUT_CONFIG_DRAG_LOCK_DISABLED = 0,
    LIBINPUT_CONFIG_DRAG_LOCK_ENABLED = 1,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_config_send_events_mode {
    LIBINPUT_CONFIG_SEND_EVENTS_ENABLED = 0,
    LIBINPUT_CONFIG_SEND_EVENTS_DISABLED = 1,
    LIBINPUT_CONFIG_SEND_EVENTS_DISABLED_ON_EXTERNAL_MOUSE = 2,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_config_accel_profile {
    LIBINPUT_CONFIG_ACCEL_PROFILE_NONE = 0,
    LIBINPUT_CONFIG_ACCEL_PROFILE_FLAT = 1,
    LIBINPUT_CONFIG_ACCEL_PROFILE_ADAPTIVE = 2,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_config_click_method {
    LIBINPUT_CONFIG_CLICK_METHOD_NONE = 0,
    LIBINPUT_CONFIG_CLICK_METHOD_BUTTON_AREAS = 1,
    LIBINPUT_CONFIG_CLICK_METHOD_CLICKFINGER = 2,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_config_middle_emulation_state {
    LIBINPUT_CONFIG_MIDDLE_EMULATION_DISABLED = 0,
    LIBINPUT_CONFIG_MIDDLE_EMULATION_ENABLED = 1,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_config_scroll_method {
    LIBINPUT_CONFIG_SCROLL_NO_SCROLL = 0,
    LIBINPUT_CONFIG_SCROLL_2FG = 1,
    LIBINPUT_CONFIG_SCROLL_EDGE = 2,
    LIBINPUT_CONFIG_SCROLL_ON_BUTTON_DOWN = 4,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum libinput_config_dwt_state {
    LIBINPUT_CONFIG_DWT_DISABLED = 0,
    LIBINPUT_CONFIG_DWT_ENABLED = 1,
}
pub type __builtin_va_list = [__va_list_tag; 1usize];
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct __va_list_tag {
    pub gp_offset: ::std::os::raw::c_uint,
    pub fp_offset: ::std::os::raw::c_uint,
    pub overflow_arg_area: *mut ::std::os::raw::c_void,
    pub reg_save_area: *mut ::std::os::raw::c_void,
}
impl ::std::default::Default for __va_list_tag {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}

#[link(name = "input")]
#[link(name = "udev")]
extern "C" {
    pub fn __ctype_get_mb_cur_max() -> size_t;
    pub fn atof(__nptr: *const ::std::os::raw::c_char) -> f64;
    pub fn atoi(__nptr: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn atol(__nptr: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_long;
    pub fn atoll(__nptr: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_longlong;
    pub fn strtod(__nptr: *const ::std::os::raw::c_char,
                  __endptr: *mut *mut ::std::os::raw::c_char) -> f64;
    pub fn strtof(__nptr: *const ::std::os::raw::c_char,
                  __endptr: *mut *mut ::std::os::raw::c_char) -> f32;
    pub fn strtold(__nptr: *const ::std::os::raw::c_char,
                   __endptr: *mut *mut ::std::os::raw::c_char) -> f64;
    pub fn strtol(__nptr: *const ::std::os::raw::c_char,
                  __endptr: *mut *mut ::std::os::raw::c_char,
                  __base: ::std::os::raw::c_int) -> ::std::os::raw::c_long;
    pub fn strtoul(__nptr: *const ::std::os::raw::c_char,
                   __endptr: *mut *mut ::std::os::raw::c_char,
                   __base: ::std::os::raw::c_int) -> ::std::os::raw::c_ulong;
    pub fn strtoq(__nptr: *const ::std::os::raw::c_char,
                  __endptr: *mut *mut ::std::os::raw::c_char,
                  __base: ::std::os::raw::c_int)
     -> ::std::os::raw::c_longlong;
    pub fn strtouq(__nptr: *const ::std::os::raw::c_char,
                   __endptr: *mut *mut ::std::os::raw::c_char,
                   __base: ::std::os::raw::c_int)
     -> ::std::os::raw::c_ulonglong;
    pub fn strtoll(__nptr: *const ::std::os::raw::c_char,
                   __endptr: *mut *mut ::std::os::raw::c_char,
                   __base: ::std::os::raw::c_int)
     -> ::std::os::raw::c_longlong;
    pub fn strtoull(__nptr: *const ::std::os::raw::c_char,
                    __endptr: *mut *mut ::std::os::raw::c_char,
                    __base: ::std::os::raw::c_int)
     -> ::std::os::raw::c_ulonglong;
    pub fn l64a(__n: ::std::os::raw::c_long) -> *mut ::std::os::raw::c_char;
    pub fn a64l(__s: *const ::std::os::raw::c_char) -> ::std::os::raw::c_long;
    pub fn select(__nfds: ::std::os::raw::c_int, __readfds: *mut fd_set,
                  __writefds: *mut fd_set, __exceptfds: *mut fd_set,
                  __timeout: *mut timeval) -> ::std::os::raw::c_int;
    pub fn pselect(__nfds: ::std::os::raw::c_int, __readfds: *mut fd_set,
                   __writefds: *mut fd_set, __exceptfds: *mut fd_set,
                   __timeout: *const timespec, __sigmask: *const __sigset_t)
     -> ::std::os::raw::c_int;
    pub fn gnu_dev_major(__dev: ::std::os::raw::c_ulonglong)
     -> ::std::os::raw::c_uint;
    pub fn gnu_dev_minor(__dev: ::std::os::raw::c_ulonglong)
     -> ::std::os::raw::c_uint;
    pub fn gnu_dev_makedev(__major: ::std::os::raw::c_uint,
                           __minor: ::std::os::raw::c_uint)
     -> ::std::os::raw::c_ulonglong;
    pub fn random() -> ::std::os::raw::c_long;
    pub fn srandom(__seed: ::std::os::raw::c_uint);
    pub fn initstate(__seed: ::std::os::raw::c_uint,
                     __statebuf: *mut ::std::os::raw::c_char,
                     __statelen: size_t) -> *mut ::std::os::raw::c_char;
    pub fn setstate(__statebuf: *mut ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn random_r(__buf: *mut random_data, __result: *mut int32_t)
     -> ::std::os::raw::c_int;
    pub fn srandom_r(__seed: ::std::os::raw::c_uint, __buf: *mut random_data)
     -> ::std::os::raw::c_int;
    pub fn initstate_r(__seed: ::std::os::raw::c_uint,
                       __statebuf: *mut ::std::os::raw::c_char,
                       __statelen: size_t, __buf: *mut random_data)
     -> ::std::os::raw::c_int;
    pub fn setstate_r(__statebuf: *mut ::std::os::raw::c_char,
                      __buf: *mut random_data) -> ::std::os::raw::c_int;
    pub fn rand() -> ::std::os::raw::c_int;
    pub fn srand(__seed: ::std::os::raw::c_uint);
    pub fn rand_r(__seed: *mut ::std::os::raw::c_uint)
     -> ::std::os::raw::c_int;
    pub fn drand48() -> f64;
    pub fn erand48(__xsubi: *mut ::std::os::raw::c_ushort) -> f64;
    pub fn lrand48() -> ::std::os::raw::c_long;
    pub fn nrand48(__xsubi: *mut ::std::os::raw::c_ushort)
     -> ::std::os::raw::c_long;
    pub fn mrand48() -> ::std::os::raw::c_long;
    pub fn jrand48(__xsubi: *mut ::std::os::raw::c_ushort)
     -> ::std::os::raw::c_long;
    pub fn srand48(__seedval: ::std::os::raw::c_long);
    pub fn seed48(__seed16v: *mut ::std::os::raw::c_ushort)
     -> *mut ::std::os::raw::c_ushort;
    pub fn lcong48(__param: *mut ::std::os::raw::c_ushort);
    pub fn drand48_r(__buffer: *mut drand48_data, __result: *mut f64)
     -> ::std::os::raw::c_int;
    pub fn erand48_r(__xsubi: *mut ::std::os::raw::c_ushort,
                     __buffer: *mut drand48_data, __result: *mut f64)
     -> ::std::os::raw::c_int;
    pub fn lrand48_r(__buffer: *mut drand48_data,
                     __result: *mut ::std::os::raw::c_long)
     -> ::std::os::raw::c_int;
    pub fn nrand48_r(__xsubi: *mut ::std::os::raw::c_ushort,
                     __buffer: *mut drand48_data,
                     __result: *mut ::std::os::raw::c_long)
     -> ::std::os::raw::c_int;
    pub fn mrand48_r(__buffer: *mut drand48_data,
                     __result: *mut ::std::os::raw::c_long)
     -> ::std::os::raw::c_int;
    pub fn jrand48_r(__xsubi: *mut ::std::os::raw::c_ushort,
                     __buffer: *mut drand48_data,
                     __result: *mut ::std::os::raw::c_long)
     -> ::std::os::raw::c_int;
    pub fn srand48_r(__seedval: ::std::os::raw::c_long,
                     __buffer: *mut drand48_data) -> ::std::os::raw::c_int;
    pub fn seed48_r(__seed16v: *mut ::std::os::raw::c_ushort,
                    __buffer: *mut drand48_data) -> ::std::os::raw::c_int;
    pub fn lcong48_r(__param: *mut ::std::os::raw::c_ushort,
                     __buffer: *mut drand48_data) -> ::std::os::raw::c_int;
    pub fn malloc(__size: size_t) -> *mut ::std::os::raw::c_void;
    pub fn calloc(__nmemb: size_t, __size: size_t)
     -> *mut ::std::os::raw::c_void;
    pub fn realloc(__ptr: *mut ::std::os::raw::c_void, __size: size_t)
     -> *mut ::std::os::raw::c_void;
    pub fn free(__ptr: *mut ::std::os::raw::c_void);
    pub fn cfree(__ptr: *mut ::std::os::raw::c_void);
    pub fn alloca(__size: size_t) -> *mut ::std::os::raw::c_void;
    pub fn valloc(__size: size_t) -> *mut ::std::os::raw::c_void;
    pub fn posix_memalign(__memptr: *mut *mut ::std::os::raw::c_void,
                          __alignment: size_t, __size: size_t)
     -> ::std::os::raw::c_int;
    pub fn aligned_alloc(__alignment: size_t, __size: size_t)
     -> *mut ::std::os::raw::c_void;
    pub fn abort();
    pub fn atexit(__func: ::std::option::Option<extern "C" fn()>)
     -> ::std::os::raw::c_int;
    pub fn at_quick_exit(__func: ::std::option::Option<extern "C" fn()>)
     -> ::std::os::raw::c_int;
    pub fn on_exit(__func:
                       ::std::option::Option<unsafe extern "C" fn(__status:
                                                                      ::std::os::raw::c_int,
                                                                  __arg:
                                                                      *mut ::std::os::raw::c_void)>,
                   __arg: *mut ::std::os::raw::c_void)
     -> ::std::os::raw::c_int;
    pub fn exit(__status: ::std::os::raw::c_int);
    pub fn quick_exit(__status: ::std::os::raw::c_int);
    pub fn _Exit(__status: ::std::os::raw::c_int);
    pub fn getenv(__name: *const ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn putenv(__string: *mut ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn setenv(__name: *const ::std::os::raw::c_char,
                  __value: *const ::std::os::raw::c_char,
                  __replace: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn unsetenv(__name: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn clearenv() -> ::std::os::raw::c_int;
    pub fn mktemp(__template: *mut ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn mkstemp(__template: *mut ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn mkstemps(__template: *mut ::std::os::raw::c_char,
                    __suffixlen: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn mkdtemp(__template: *mut ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn system(__command: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn realpath(__name: *const ::std::os::raw::c_char,
                    __resolved: *mut ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn bsearch(__key: *const ::std::os::raw::c_void,
                   __base: *const ::std::os::raw::c_void, __nmemb: size_t,
                   __size: size_t, __compar: __compar_fn_t)
     -> *mut ::std::os::raw::c_void;
    pub fn qsort(__base: *mut ::std::os::raw::c_void, __nmemb: size_t,
                 __size: size_t, __compar: __compar_fn_t);
    pub fn abs(__x: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
    pub fn labs(__x: ::std::os::raw::c_long) -> ::std::os::raw::c_long;
    pub fn llabs(__x: ::std::os::raw::c_longlong)
     -> ::std::os::raw::c_longlong;
    pub fn div(__numer: ::std::os::raw::c_int, __denom: ::std::os::raw::c_int)
     -> div_t;
    pub fn ldiv(__numer: ::std::os::raw::c_long,
                __denom: ::std::os::raw::c_long) -> ldiv_t;
    pub fn lldiv(__numer: ::std::os::raw::c_longlong,
                 __denom: ::std::os::raw::c_longlong) -> lldiv_t;
    pub fn ecvt(__value: f64, __ndigit: ::std::os::raw::c_int,
                __decpt: *mut ::std::os::raw::c_int,
                __sign: *mut ::std::os::raw::c_int)
     -> *mut ::std::os::raw::c_char;
    pub fn fcvt(__value: f64, __ndigit: ::std::os::raw::c_int,
                __decpt: *mut ::std::os::raw::c_int,
                __sign: *mut ::std::os::raw::c_int)
     -> *mut ::std::os::raw::c_char;
    pub fn gcvt(__value: f64, __ndigit: ::std::os::raw::c_int,
                __buf: *mut ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn qecvt(__value: f64, __ndigit: ::std::os::raw::c_int,
                 __decpt: *mut ::std::os::raw::c_int,
                 __sign: *mut ::std::os::raw::c_int)
     -> *mut ::std::os::raw::c_char;
    pub fn qfcvt(__value: f64, __ndigit: ::std::os::raw::c_int,
                 __decpt: *mut ::std::os::raw::c_int,
                 __sign: *mut ::std::os::raw::c_int)
     -> *mut ::std::os::raw::c_char;
    pub fn qgcvt(__value: f64, __ndigit: ::std::os::raw::c_int,
                 __buf: *mut ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn ecvt_r(__value: f64, __ndigit: ::std::os::raw::c_int,
                  __decpt: *mut ::std::os::raw::c_int,
                  __sign: *mut ::std::os::raw::c_int,
                  __buf: *mut ::std::os::raw::c_char, __len: size_t)
     -> ::std::os::raw::c_int;
    pub fn fcvt_r(__value: f64, __ndigit: ::std::os::raw::c_int,
                  __decpt: *mut ::std::os::raw::c_int,
                  __sign: *mut ::std::os::raw::c_int,
                  __buf: *mut ::std::os::raw::c_char, __len: size_t)
     -> ::std::os::raw::c_int;
    pub fn qecvt_r(__value: f64, __ndigit: ::std::os::raw::c_int,
                   __decpt: *mut ::std::os::raw::c_int,
                   __sign: *mut ::std::os::raw::c_int,
                   __buf: *mut ::std::os::raw::c_char, __len: size_t)
     -> ::std::os::raw::c_int;
    pub fn qfcvt_r(__value: f64, __ndigit: ::std::os::raw::c_int,
                   __decpt: *mut ::std::os::raw::c_int,
                   __sign: *mut ::std::os::raw::c_int,
                   __buf: *mut ::std::os::raw::c_char, __len: size_t)
     -> ::std::os::raw::c_int;
    pub fn mblen(__s: *const ::std::os::raw::c_char, __n: size_t)
     -> ::std::os::raw::c_int;
    pub fn mbtowc(__pwc: *mut wchar_t, __s: *const ::std::os::raw::c_char,
                  __n: size_t) -> ::std::os::raw::c_int;
    pub fn wctomb(__s: *mut ::std::os::raw::c_char, __wchar: wchar_t)
     -> ::std::os::raw::c_int;
    pub fn mbstowcs(__pwcs: *mut wchar_t, __s: *const ::std::os::raw::c_char,
                    __n: size_t) -> size_t;
    pub fn wcstombs(__s: *mut ::std::os::raw::c_char, __pwcs: *const wchar_t,
                    __n: size_t) -> size_t;
    pub fn rpmatch(__response: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn getsubopt(__optionp: *mut *mut ::std::os::raw::c_char,
                     __tokens: *const *mut ::std::os::raw::c_char,
                     __valuep: *mut *mut ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn getloadavg(__loadavg: *mut f64, __nelem: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn udev_ref(udev: *mut udev) -> *mut udev;
    pub fn udev_unref(udev: *mut udev) -> *mut udev;
    pub fn udev_new() -> *mut udev;
    pub fn udev_set_log_fn(udev: *mut udev,
                           log_fn:
                               ::std::option::Option<unsafe extern "C" fn(udev:
                                                                              *mut udev,
                                                                          priority:
                                                                              ::std::os::raw::c_int,
                                                                          file:
                                                                              *const ::std::os::raw::c_char,
                                                                          line:
                                                                              ::std::os::raw::c_int,
                                                                          fn_:
                                                                              *const ::std::os::raw::c_char,
                                                                          format:
                                                                              *const ::std::os::raw::c_char,
                                                                          args:
                                                                              va_list)>);
    pub fn udev_get_log_priority(udev: *mut udev) -> ::std::os::raw::c_int;
    pub fn udev_set_log_priority(udev: *mut udev,
                                 priority: ::std::os::raw::c_int);
    pub fn udev_get_userdata(udev: *mut udev) -> *mut ::std::os::raw::c_void;
    pub fn udev_set_userdata(udev: *mut udev,
                             userdata: *mut ::std::os::raw::c_void);
    pub fn udev_list_entry_get_next(list_entry: *mut udev_list_entry)
     -> *mut udev_list_entry;
    pub fn udev_list_entry_get_by_name(list_entry: *mut udev_list_entry,
                                       name: *const ::std::os::raw::c_char)
     -> *mut udev_list_entry;
    pub fn udev_list_entry_get_name(list_entry: *mut udev_list_entry)
     -> *const ::std::os::raw::c_char;
    pub fn udev_list_entry_get_value(list_entry: *mut udev_list_entry)
     -> *const ::std::os::raw::c_char;
    pub fn udev_device_ref(udev_device: *mut udev_device) -> *mut udev_device;
    pub fn udev_device_unref(udev_device: *mut udev_device)
     -> *mut udev_device;
    pub fn udev_device_get_udev(udev_device: *mut udev_device) -> *mut udev;
    pub fn udev_device_new_from_syspath(udev: *mut udev,
                                        syspath:
                                            *const ::std::os::raw::c_char)
     -> *mut udev_device;
    pub fn udev_device_new_from_devnum(udev: *mut udev,
                                       type_: ::std::os::raw::c_char,
                                       devnum: dev_t) -> *mut udev_device;
    pub fn udev_device_new_from_subsystem_sysname(udev: *mut udev,
                                                  subsystem:
                                                      *const ::std::os::raw::c_char,
                                                  sysname:
                                                      *const ::std::os::raw::c_char)
     -> *mut udev_device;
    pub fn udev_device_new_from_device_id(udev: *mut udev,
                                          id: *const ::std::os::raw::c_char)
     -> *mut udev_device;
    pub fn udev_device_new_from_environment(udev: *mut udev)
     -> *mut udev_device;
    pub fn udev_device_get_parent(udev_device: *mut udev_device)
     -> *mut udev_device;
    pub fn udev_device_get_parent_with_subsystem_devtype(udev_device:
                                                             *mut udev_device,
                                                         subsystem:
                                                             *const ::std::os::raw::c_char,
                                                         devtype:
                                                             *const ::std::os::raw::c_char)
     -> *mut udev_device;
    pub fn udev_device_get_devpath(udev_device: *mut udev_device)
     -> *const ::std::os::raw::c_char;
    pub fn udev_device_get_subsystem(udev_device: *mut udev_device)
     -> *const ::std::os::raw::c_char;
    pub fn udev_device_get_devtype(udev_device: *mut udev_device)
     -> *const ::std::os::raw::c_char;
    pub fn udev_device_get_syspath(udev_device: *mut udev_device)
     -> *const ::std::os::raw::c_char;
    pub fn udev_device_get_sysname(udev_device: *mut udev_device)
     -> *const ::std::os::raw::c_char;
    pub fn udev_device_get_sysnum(udev_device: *mut udev_device)
     -> *const ::std::os::raw::c_char;
    pub fn udev_device_get_devnode(udev_device: *mut udev_device)
     -> *const ::std::os::raw::c_char;
    pub fn udev_device_get_is_initialized(udev_device: *mut udev_device)
     -> ::std::os::raw::c_int;
    pub fn udev_device_get_devlinks_list_entry(udev_device: *mut udev_device)
     -> *mut udev_list_entry;
    pub fn udev_device_get_properties_list_entry(udev_device:
                                                     *mut udev_device)
     -> *mut udev_list_entry;
    pub fn udev_device_get_tags_list_entry(udev_device: *mut udev_device)
     -> *mut udev_list_entry;
    pub fn udev_device_get_sysattr_list_entry(udev_device: *mut udev_device)
     -> *mut udev_list_entry;
    pub fn udev_device_get_property_value(udev_device: *mut udev_device,
                                          key: *const ::std::os::raw::c_char)
     -> *const ::std::os::raw::c_char;
    pub fn udev_device_get_driver(udev_device: *mut udev_device)
     -> *const ::std::os::raw::c_char;
    pub fn udev_device_get_devnum(udev_device: *mut udev_device) -> dev_t;
    pub fn udev_device_get_action(udev_device: *mut udev_device)
     -> *const ::std::os::raw::c_char;
    pub fn udev_device_get_seqnum(udev_device: *mut udev_device)
     -> ::std::os::raw::c_ulonglong;
    pub fn udev_device_get_usec_since_initialized(udev_device:
                                                      *mut udev_device)
     -> ::std::os::raw::c_ulonglong;
    pub fn udev_device_get_sysattr_value(udev_device: *mut udev_device,
                                         sysattr:
                                             *const ::std::os::raw::c_char)
     -> *const ::std::os::raw::c_char;
    pub fn udev_device_set_sysattr_value(udev_device: *mut udev_device,
                                         sysattr:
                                             *const ::std::os::raw::c_char,
                                         value: *mut ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn udev_device_has_tag(udev_device: *mut udev_device,
                               tag: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn udev_monitor_ref(udev_monitor: *mut udev_monitor)
     -> *mut udev_monitor;
    pub fn udev_monitor_unref(udev_monitor: *mut udev_monitor)
     -> *mut udev_monitor;
    pub fn udev_monitor_get_udev(udev_monitor: *mut udev_monitor)
     -> *mut udev;
    pub fn udev_monitor_new_from_netlink(udev: *mut udev,
                                         name: *const ::std::os::raw::c_char)
     -> *mut udev_monitor;
    pub fn udev_monitor_enable_receiving(udev_monitor: *mut udev_monitor)
     -> ::std::os::raw::c_int;
    pub fn udev_monitor_set_receive_buffer_size(udev_monitor:
                                                    *mut udev_monitor,
                                                size: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn udev_monitor_get_fd(udev_monitor: *mut udev_monitor)
     -> ::std::os::raw::c_int;
    pub fn udev_monitor_receive_device(udev_monitor: *mut udev_monitor)
     -> *mut udev_device;
    pub fn udev_monitor_filter_add_match_subsystem_devtype(udev_monitor:
                                                               *mut udev_monitor,
                                                           subsystem:
                                                               *const ::std::os::raw::c_char,
                                                           devtype:
                                                               *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn udev_monitor_filter_add_match_tag(udev_monitor: *mut udev_monitor,
                                             tag:
                                                 *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn udev_monitor_filter_update(udev_monitor: *mut udev_monitor)
     -> ::std::os::raw::c_int;
    pub fn udev_monitor_filter_remove(udev_monitor: *mut udev_monitor)
     -> ::std::os::raw::c_int;
    pub fn udev_enumerate_ref(udev_enumerate: *mut udev_enumerate)
     -> *mut udev_enumerate;
    pub fn udev_enumerate_unref(udev_enumerate: *mut udev_enumerate)
     -> *mut udev_enumerate;
    pub fn udev_enumerate_get_udev(udev_enumerate: *mut udev_enumerate)
     -> *mut udev;
    pub fn udev_enumerate_new(udev: *mut udev) -> *mut udev_enumerate;
    pub fn udev_enumerate_add_match_subsystem(udev_enumerate:
                                                  *mut udev_enumerate,
                                              subsystem:
                                                  *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn udev_enumerate_add_nomatch_subsystem(udev_enumerate:
                                                    *mut udev_enumerate,
                                                subsystem:
                                                    *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn udev_enumerate_add_match_sysattr(udev_enumerate:
                                                *mut udev_enumerate,
                                            sysattr:
                                                *const ::std::os::raw::c_char,
                                            value:
                                                *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn udev_enumerate_add_nomatch_sysattr(udev_enumerate:
                                                  *mut udev_enumerate,
                                              sysattr:
                                                  *const ::std::os::raw::c_char,
                                              value:
                                                  *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn udev_enumerate_add_match_property(udev_enumerate:
                                                 *mut udev_enumerate,
                                             property:
                                                 *const ::std::os::raw::c_char,
                                             value:
                                                 *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn udev_enumerate_add_match_sysname(udev_enumerate:
                                                *mut udev_enumerate,
                                            sysname:
                                                *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn udev_enumerate_add_match_tag(udev_enumerate: *mut udev_enumerate,
                                        tag: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn udev_enumerate_add_match_parent(udev_enumerate:
                                               *mut udev_enumerate,
                                           parent: *mut udev_device)
     -> ::std::os::raw::c_int;
    pub fn udev_enumerate_add_match_is_initialized(udev_enumerate:
                                                       *mut udev_enumerate)
     -> ::std::os::raw::c_int;
    pub fn udev_enumerate_add_syspath(udev_enumerate: *mut udev_enumerate,
                                      syspath: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn udev_enumerate_scan_devices(udev_enumerate: *mut udev_enumerate)
     -> ::std::os::raw::c_int;
    pub fn udev_enumerate_scan_subsystems(udev_enumerate: *mut udev_enumerate)
     -> ::std::os::raw::c_int;
    pub fn udev_enumerate_get_list_entry(udev_enumerate: *mut udev_enumerate)
     -> *mut udev_list_entry;
    pub fn udev_queue_ref(udev_queue: *mut udev_queue) -> *mut udev_queue;
    pub fn udev_queue_unref(udev_queue: *mut udev_queue) -> *mut udev_queue;
    pub fn udev_queue_get_udev(udev_queue: *mut udev_queue) -> *mut udev;
    pub fn udev_queue_new(udev: *mut udev) -> *mut udev_queue;
    pub fn udev_queue_get_kernel_seqnum(udev_queue: *mut udev_queue)
     -> ::std::os::raw::c_ulonglong;
    pub fn udev_queue_get_udev_seqnum(udev_queue: *mut udev_queue)
     -> ::std::os::raw::c_ulonglong;
    pub fn udev_queue_get_udev_is_active(udev_queue: *mut udev_queue)
     -> ::std::os::raw::c_int;
    pub fn udev_queue_get_queue_is_empty(udev_queue: *mut udev_queue)
     -> ::std::os::raw::c_int;
    pub fn udev_queue_get_seqnum_is_finished(udev_queue: *mut udev_queue,
                                             seqnum:
                                                 ::std::os::raw::c_ulonglong)
     -> ::std::os::raw::c_int;
    pub fn udev_queue_get_seqnum_sequence_is_finished(udev_queue:
                                                          *mut udev_queue,
                                                      start:
                                                          ::std::os::raw::c_ulonglong,
                                                      end:
                                                          ::std::os::raw::c_ulonglong)
     -> ::std::os::raw::c_int;
    pub fn udev_queue_get_fd(udev_queue: *mut udev_queue)
     -> ::std::os::raw::c_int;
    pub fn udev_queue_flush(udev_queue: *mut udev_queue)
     -> ::std::os::raw::c_int;
    pub fn udev_queue_get_queued_list_entry(udev_queue: *mut udev_queue)
     -> *mut udev_list_entry;
    pub fn udev_hwdb_new(udev: *mut udev) -> *mut udev_hwdb;
    pub fn udev_hwdb_ref(hwdb: *mut udev_hwdb) -> *mut udev_hwdb;
    pub fn udev_hwdb_unref(hwdb: *mut udev_hwdb) -> *mut udev_hwdb;
    pub fn udev_hwdb_get_properties_list_entry(hwdb: *mut udev_hwdb,
                                               modalias:
                                                   *const ::std::os::raw::c_char,
                                               flags: ::std::os::raw::c_uint)
     -> *mut udev_list_entry;
    pub fn udev_util_encode_string(str: *const ::std::os::raw::c_char,
                                   str_enc: *mut ::std::os::raw::c_char,
                                   len: size_t) -> ::std::os::raw::c_int;
    pub fn libinput_device_tablet_pad_get_num_mode_groups(device:
                                                              *mut libinput_device)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_tablet_pad_get_mode_group(device:
                                                         *mut libinput_device,
                                                     index:
                                                         ::std::os::raw::c_uint)
     -> *mut libinput_tablet_pad_mode_group;
    pub fn libinput_tablet_pad_mode_group_get_index(group:
                                                        *mut libinput_tablet_pad_mode_group)
     -> ::std::os::raw::c_uint;
    pub fn libinput_tablet_pad_mode_group_get_num_modes(group:
                                                            *mut libinput_tablet_pad_mode_group)
     -> ::std::os::raw::c_uint;
    pub fn libinput_tablet_pad_mode_group_get_mode(group:
                                                       *mut libinput_tablet_pad_mode_group)
     -> ::std::os::raw::c_uint;
    pub fn libinput_tablet_pad_mode_group_has_button(group:
                                                         *mut libinput_tablet_pad_mode_group,
                                                     button:
                                                         ::std::os::raw::c_uint)
     -> ::std::os::raw::c_int;
    pub fn libinput_tablet_pad_mode_group_has_ring(group:
                                                       *mut libinput_tablet_pad_mode_group,
                                                   ring:
                                                       ::std::os::raw::c_uint)
     -> ::std::os::raw::c_int;
    pub fn libinput_tablet_pad_mode_group_has_strip(group:
                                                        *mut libinput_tablet_pad_mode_group,
                                                    strip:
                                                        ::std::os::raw::c_uint)
     -> ::std::os::raw::c_int;
    pub fn libinput_tablet_pad_mode_group_button_is_toggle(group:
                                                               *mut libinput_tablet_pad_mode_group,
                                                           button:
                                                               ::std::os::raw::c_uint)
     -> ::std::os::raw::c_int;
    pub fn libinput_tablet_pad_mode_group_ref(group:
                                                  *mut libinput_tablet_pad_mode_group)
     -> *mut libinput_tablet_pad_mode_group;
    pub fn libinput_tablet_pad_mode_group_unref(group:
                                                    *mut libinput_tablet_pad_mode_group)
     -> *mut libinput_tablet_pad_mode_group;
    pub fn libinput_tablet_pad_mode_group_set_user_data(group:
                                                            *mut libinput_tablet_pad_mode_group,
                                                        user_data:
                                                            *mut ::std::os::raw::c_void);
    pub fn libinput_tablet_pad_mode_group_get_user_data(group:
                                                            *mut libinput_tablet_pad_mode_group)
     -> *mut ::std::os::raw::c_void;
    pub fn libinput_event_destroy(event: *mut libinput_event);
    pub fn libinput_event_get_type(event: *mut libinput_event)
     -> libinput_event_type;
    pub fn libinput_event_get_context(event: *mut libinput_event)
     -> *mut libinput;
    pub fn libinput_event_get_device(event: *mut libinput_event)
     -> *mut libinput_device;
    pub fn libinput_event_get_pointer_event(event: *mut libinput_event)
     -> *mut libinput_event_pointer;
    pub fn libinput_event_get_keyboard_event(event: *mut libinput_event)
     -> *mut libinput_event_keyboard;
    pub fn libinput_event_get_touch_event(event: *mut libinput_event)
     -> *mut libinput_event_touch;
    pub fn libinput_event_get_gesture_event(event: *mut libinput_event)
     -> *mut libinput_event_gesture;
    pub fn libinput_event_get_tablet_tool_event(event: *mut libinput_event)
     -> *mut libinput_event_tablet_tool;
    pub fn libinput_event_get_tablet_pad_event(event: *mut libinput_event)
     -> *mut libinput_event_tablet_pad;
    pub fn libinput_event_get_device_notify_event(event: *mut libinput_event)
     -> *mut libinput_event_device_notify;
    pub fn libinput_event_device_notify_get_base_event(event:
                                                           *mut libinput_event_device_notify)
     -> *mut libinput_event;
    pub fn libinput_event_keyboard_get_time(event:
                                                *mut libinput_event_keyboard)
     -> uint32_t;
    pub fn libinput_event_keyboard_get_time_usec(event:
                                                     *mut libinput_event_keyboard)
     -> uint64_t;
    pub fn libinput_event_keyboard_get_key(event:
                                               *mut libinput_event_keyboard)
     -> uint32_t;
    pub fn libinput_event_keyboard_get_key_state(event:
                                                     *mut libinput_event_keyboard)
     -> libinput_key_state;
    pub fn libinput_event_keyboard_get_base_event(event:
                                                      *mut libinput_event_keyboard)
     -> *mut libinput_event;
    pub fn libinput_event_keyboard_get_seat_key_count(event:
                                                          *mut libinput_event_keyboard)
     -> uint32_t;
    pub fn libinput_event_pointer_get_time(event: *mut libinput_event_pointer)
     -> uint32_t;
    pub fn libinput_event_pointer_get_time_usec(event:
                                                    *mut libinput_event_pointer)
     -> uint64_t;
    pub fn libinput_event_pointer_get_dx(event: *mut libinput_event_pointer)
     -> f64;
    pub fn libinput_event_pointer_get_dy(event: *mut libinput_event_pointer)
     -> f64;
    pub fn libinput_event_pointer_get_dx_unaccelerated(event:
                                                           *mut libinput_event_pointer)
     -> f64;
    pub fn libinput_event_pointer_get_dy_unaccelerated(event:
                                                           *mut libinput_event_pointer)
     -> f64;
    pub fn libinput_event_pointer_get_absolute_x(event:
                                                     *mut libinput_event_pointer)
     -> f64;
    pub fn libinput_event_pointer_get_absolute_y(event:
                                                     *mut libinput_event_pointer)
     -> f64;
    pub fn libinput_event_pointer_get_absolute_x_transformed(event:
                                                                 *mut libinput_event_pointer,
                                                             width: uint32_t)
     -> f64;
    pub fn libinput_event_pointer_get_absolute_y_transformed(event:
                                                                 *mut libinput_event_pointer,
                                                             height: uint32_t)
     -> f64;
    pub fn libinput_event_pointer_get_button(event:
                                                 *mut libinput_event_pointer)
     -> uint32_t;
    pub fn libinput_event_pointer_get_button_state(event:
                                                       *mut libinput_event_pointer)
     -> libinput_button_state;
    pub fn libinput_event_pointer_get_seat_button_count(event:
                                                            *mut libinput_event_pointer)
     -> uint32_t;
    pub fn libinput_event_pointer_has_axis(event: *mut libinput_event_pointer,
                                           axis: libinput_pointer_axis)
     -> ::std::os::raw::c_int;
    pub fn libinput_event_pointer_get_axis_value(event:
                                                     *mut libinput_event_pointer,
                                                 axis: libinput_pointer_axis)
     -> f64;
    pub fn libinput_event_pointer_get_axis_source(event:
                                                      *mut libinput_event_pointer)
     -> libinput_pointer_axis_source;
    pub fn libinput_event_pointer_get_axis_value_discrete(event:
                                                              *mut libinput_event_pointer,
                                                          axis:
                                                              libinput_pointer_axis)
     -> f64;
    pub fn libinput_event_pointer_get_base_event(event:
                                                     *mut libinput_event_pointer)
     -> *mut libinput_event;
    pub fn libinput_event_touch_get_time(event: *mut libinput_event_touch)
     -> uint32_t;
    pub fn libinput_event_touch_get_time_usec(event:
                                                  *mut libinput_event_touch)
     -> uint64_t;
    pub fn libinput_event_touch_get_slot(event: *mut libinput_event_touch)
     -> int32_t;
    pub fn libinput_event_touch_get_seat_slot(event:
                                                  *mut libinput_event_touch)
     -> int32_t;
    pub fn libinput_event_touch_get_x(event: *mut libinput_event_touch)
     -> f64;
    pub fn libinput_event_touch_get_y(event: *mut libinput_event_touch)
     -> f64;
    pub fn libinput_event_touch_get_x_transformed(event:
                                                      *mut libinput_event_touch,
                                                  width: uint32_t) -> f64;
    pub fn libinput_event_touch_get_y_transformed(event:
                                                      *mut libinput_event_touch,
                                                  height: uint32_t) -> f64;
    pub fn libinput_event_touch_get_base_event(event:
                                                   *mut libinput_event_touch)
     -> *mut libinput_event;
    pub fn libinput_event_gesture_get_time(event: *mut libinput_event_gesture)
     -> uint32_t;
    pub fn libinput_event_gesture_get_time_usec(event:
                                                    *mut libinput_event_gesture)
     -> uint64_t;
    pub fn libinput_event_gesture_get_base_event(event:
                                                     *mut libinput_event_gesture)
     -> *mut libinput_event;
    pub fn libinput_event_gesture_get_finger_count(event:
                                                       *mut libinput_event_gesture)
     -> ::std::os::raw::c_int;
    pub fn libinput_event_gesture_get_cancelled(event:
                                                    *mut libinput_event_gesture)
     -> ::std::os::raw::c_int;
    pub fn libinput_event_gesture_get_dx(event: *mut libinput_event_gesture)
     -> f64;
    pub fn libinput_event_gesture_get_dy(event: *mut libinput_event_gesture)
     -> f64;
    pub fn libinput_event_gesture_get_dx_unaccelerated(event:
                                                           *mut libinput_event_gesture)
     -> f64;
    pub fn libinput_event_gesture_get_dy_unaccelerated(event:
                                                           *mut libinput_event_gesture)
     -> f64;
    pub fn libinput_event_gesture_get_scale(event:
                                                *mut libinput_event_gesture)
     -> f64;
    pub fn libinput_event_gesture_get_angle_delta(event:
                                                      *mut libinput_event_gesture)
     -> f64;
    pub fn libinput_event_tablet_tool_get_base_event(event:
                                                         *mut libinput_event_tablet_tool)
     -> *mut libinput_event;
    pub fn libinput_event_tablet_tool_x_has_changed(event:
                                                        *mut libinput_event_tablet_tool)
     -> ::std::os::raw::c_int;
    pub fn libinput_event_tablet_tool_y_has_changed(event:
                                                        *mut libinput_event_tablet_tool)
     -> ::std::os::raw::c_int;
    pub fn libinput_event_tablet_tool_pressure_has_changed(event:
                                                               *mut libinput_event_tablet_tool)
     -> ::std::os::raw::c_int;
    pub fn libinput_event_tablet_tool_distance_has_changed(event:
                                                               *mut libinput_event_tablet_tool)
     -> ::std::os::raw::c_int;
    pub fn libinput_event_tablet_tool_tilt_x_has_changed(event:
                                                             *mut libinput_event_tablet_tool)
     -> ::std::os::raw::c_int;
    pub fn libinput_event_tablet_tool_tilt_y_has_changed(event:
                                                             *mut libinput_event_tablet_tool)
     -> ::std::os::raw::c_int;
    pub fn libinput_event_tablet_tool_rotation_has_changed(event:
                                                               *mut libinput_event_tablet_tool)
     -> ::std::os::raw::c_int;
    pub fn libinput_event_tablet_tool_slider_has_changed(event:
                                                             *mut libinput_event_tablet_tool)
     -> ::std::os::raw::c_int;
    pub fn libinput_event_tablet_tool_wheel_has_changed(event:
                                                            *mut libinput_event_tablet_tool)
     -> ::std::os::raw::c_int;
    pub fn libinput_event_tablet_tool_get_x(event:
                                                *mut libinput_event_tablet_tool)
     -> f64;
    pub fn libinput_event_tablet_tool_get_y(event:
                                                *mut libinput_event_tablet_tool)
     -> f64;
    pub fn libinput_event_tablet_tool_get_dx(event:
                                                 *mut libinput_event_tablet_tool)
     -> f64;
    pub fn libinput_event_tablet_tool_get_dy(event:
                                                 *mut libinput_event_tablet_tool)
     -> f64;
    pub fn libinput_event_tablet_tool_get_pressure(event:
                                                       *mut libinput_event_tablet_tool)
     -> f64;
    pub fn libinput_event_tablet_tool_get_distance(event:
                                                       *mut libinput_event_tablet_tool)
     -> f64;
    pub fn libinput_event_tablet_tool_get_tilt_x(event:
                                                     *mut libinput_event_tablet_tool)
     -> f64;
    pub fn libinput_event_tablet_tool_get_tilt_y(event:
                                                     *mut libinput_event_tablet_tool)
     -> f64;
    pub fn libinput_event_tablet_tool_get_rotation(event:
                                                       *mut libinput_event_tablet_tool)
     -> f64;
    pub fn libinput_event_tablet_tool_get_slider_position(event:
                                                              *mut libinput_event_tablet_tool)
     -> f64;
    pub fn libinput_event_tablet_tool_get_wheel_delta(event:
                                                          *mut libinput_event_tablet_tool)
     -> f64;
    pub fn libinput_event_tablet_tool_get_wheel_delta_discrete(event:
                                                                   *mut libinput_event_tablet_tool)
     -> ::std::os::raw::c_int;
    pub fn libinput_event_tablet_tool_get_x_transformed(event:
                                                            *mut libinput_event_tablet_tool,
                                                        width: uint32_t)
     -> f64;
    pub fn libinput_event_tablet_tool_get_y_transformed(event:
                                                            *mut libinput_event_tablet_tool,
                                                        height: uint32_t)
     -> f64;
    pub fn libinput_event_tablet_tool_get_tool(event:
                                                   *mut libinput_event_tablet_tool)
     -> *mut libinput_tablet_tool;
    pub fn libinput_event_tablet_tool_get_proximity_state(event:
                                                              *mut libinput_event_tablet_tool)
     -> libinput_tablet_tool_proximity_state;
    pub fn libinput_event_tablet_tool_get_tip_state(event:
                                                        *mut libinput_event_tablet_tool)
     -> libinput_tablet_tool_tip_state;
    pub fn libinput_event_tablet_tool_get_button(event:
                                                     *mut libinput_event_tablet_tool)
     -> uint32_t;
    pub fn libinput_event_tablet_tool_get_button_state(event:
                                                           *mut libinput_event_tablet_tool)
     -> libinput_button_state;
    pub fn libinput_event_tablet_tool_get_seat_button_count(event:
                                                                *mut libinput_event_tablet_tool)
     -> uint32_t;
    pub fn libinput_event_tablet_tool_get_time(event:
                                                   *mut libinput_event_tablet_tool)
     -> uint32_t;
    pub fn libinput_event_tablet_tool_get_time_usec(event:
                                                        *mut libinput_event_tablet_tool)
     -> uint64_t;
    pub fn libinput_tablet_tool_get_type(tool: *mut libinput_tablet_tool)
     -> libinput_tablet_tool_type;
    pub fn libinput_tablet_tool_get_tool_id(tool: *mut libinput_tablet_tool)
     -> uint64_t;
    pub fn libinput_tablet_tool_ref(tool: *mut libinput_tablet_tool)
     -> *mut libinput_tablet_tool;
    pub fn libinput_tablet_tool_unref(tool: *mut libinput_tablet_tool)
     -> *mut libinput_tablet_tool;
    pub fn libinput_tablet_tool_has_pressure(tool: *mut libinput_tablet_tool)
     -> ::std::os::raw::c_int;
    pub fn libinput_tablet_tool_has_distance(tool: *mut libinput_tablet_tool)
     -> ::std::os::raw::c_int;
    pub fn libinput_tablet_tool_has_tilt(tool: *mut libinput_tablet_tool)
     -> ::std::os::raw::c_int;
    pub fn libinput_tablet_tool_has_rotation(tool: *mut libinput_tablet_tool)
     -> ::std::os::raw::c_int;
    pub fn libinput_tablet_tool_has_slider(tool: *mut libinput_tablet_tool)
     -> ::std::os::raw::c_int;
    pub fn libinput_tablet_tool_has_wheel(tool: *mut libinput_tablet_tool)
     -> ::std::os::raw::c_int;
    pub fn libinput_tablet_tool_has_button(tool: *mut libinput_tablet_tool,
                                           code: uint32_t)
     -> ::std::os::raw::c_int;
    pub fn libinput_tablet_tool_is_unique(tool: *mut libinput_tablet_tool)
     -> ::std::os::raw::c_int;
    pub fn libinput_tablet_tool_get_serial(tool: *mut libinput_tablet_tool)
     -> uint64_t;
    pub fn libinput_tablet_tool_get_user_data(tool: *mut libinput_tablet_tool)
     -> *mut ::std::os::raw::c_void;
    pub fn libinput_tablet_tool_set_user_data(tool: *mut libinput_tablet_tool,
                                              user_data:
                                                  *mut ::std::os::raw::c_void);
    pub fn libinput_event_tablet_pad_get_base_event(event:
                                                        *mut libinput_event_tablet_pad)
     -> *mut libinput_event;
    pub fn libinput_event_tablet_pad_get_ring_position(event:
                                                           *mut libinput_event_tablet_pad)
     -> f64;
    pub fn libinput_event_tablet_pad_get_ring_number(event:
                                                         *mut libinput_event_tablet_pad)
     -> ::std::os::raw::c_uint;
    pub fn libinput_event_tablet_pad_get_ring_source(event:
                                                         *mut libinput_event_tablet_pad)
     -> libinput_tablet_pad_ring_axis_source;
    pub fn libinput_event_tablet_pad_get_strip_position(event:
                                                            *mut libinput_event_tablet_pad)
     -> f64;
    pub fn libinput_event_tablet_pad_get_strip_number(event:
                                                          *mut libinput_event_tablet_pad)
     -> ::std::os::raw::c_uint;
    pub fn libinput_event_tablet_pad_get_strip_source(event:
                                                          *mut libinput_event_tablet_pad)
     -> libinput_tablet_pad_strip_axis_source;
    pub fn libinput_event_tablet_pad_get_button_number(event:
                                                           *mut libinput_event_tablet_pad)
     -> uint32_t;
    pub fn libinput_event_tablet_pad_get_button_state(event:
                                                          *mut libinput_event_tablet_pad)
     -> libinput_button_state;
    pub fn libinput_event_tablet_pad_get_mode(event:
                                                  *mut libinput_event_tablet_pad)
     -> ::std::os::raw::c_uint;
    pub fn libinput_event_tablet_pad_get_mode_group(event:
                                                        *mut libinput_event_tablet_pad)
     -> *mut libinput_tablet_pad_mode_group;
    pub fn libinput_event_tablet_pad_get_time(event:
                                                  *mut libinput_event_tablet_pad)
     -> uint32_t;
    pub fn libinput_event_tablet_pad_get_time_usec(event:
                                                       *mut libinput_event_tablet_pad)
     -> uint64_t;
    pub fn libinput_udev_create_context(interface: *const libinput_interface,
                                        user_data:
                                            *mut ::std::os::raw::c_void,
                                        udev: *mut udev) -> *mut libinput;
    pub fn libinput_udev_assign_seat(libinput: *mut libinput,
                                     seat_id: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn libinput_path_create_context(interface: *const libinput_interface,
                                        user_data:
                                            *mut ::std::os::raw::c_void)
     -> *mut libinput;
    pub fn libinput_path_add_device(libinput: *mut libinput,
                                    path: *const ::std::os::raw::c_char)
     -> *mut libinput_device;
    pub fn libinput_path_remove_device(device: *mut libinput_device);
    pub fn libinput_get_fd(libinput: *mut libinput) -> ::std::os::raw::c_int;
    pub fn libinput_dispatch(libinput: *mut libinput)
     -> ::std::os::raw::c_int;
    pub fn libinput_get_event(libinput: *mut libinput) -> *mut libinput_event;
    pub fn libinput_next_event_type(libinput: *mut libinput)
     -> libinput_event_type;
    pub fn libinput_set_user_data(libinput: *mut libinput,
                                  user_data: *mut ::std::os::raw::c_void);
    pub fn libinput_get_user_data(libinput: *mut libinput)
     -> *mut ::std::os::raw::c_void;
    pub fn libinput_resume(libinput: *mut libinput) -> ::std::os::raw::c_int;
    pub fn libinput_suspend(libinput: *mut libinput);
    pub fn libinput_ref(libinput: *mut libinput) -> *mut libinput;
    pub fn libinput_unref(libinput: *mut libinput) -> *mut libinput;
    pub fn libinput_log_set_priority(libinput: *mut libinput,
                                     priority: libinput_log_priority);
    pub fn libinput_log_get_priority(libinput: *const libinput)
     -> libinput_log_priority;
    pub fn libinput_log_set_handler(libinput: *mut libinput,
                                    log_handler: libinput_log_handler);
    pub fn libinput_seat_ref(seat: *mut libinput_seat) -> *mut libinput_seat;
    pub fn libinput_seat_unref(seat: *mut libinput_seat)
     -> *mut libinput_seat;
    pub fn libinput_seat_set_user_data(seat: *mut libinput_seat,
                                       user_data:
                                           *mut ::std::os::raw::c_void);
    pub fn libinput_seat_get_user_data(seat: *mut libinput_seat)
     -> *mut ::std::os::raw::c_void;
    pub fn libinput_seat_get_context(seat: *mut libinput_seat)
     -> *mut libinput;
    pub fn libinput_seat_get_physical_name(seat: *mut libinput_seat)
     -> *const ::std::os::raw::c_char;
    pub fn libinput_seat_get_logical_name(seat: *mut libinput_seat)
     -> *const ::std::os::raw::c_char;
    pub fn libinput_device_ref(device: *mut libinput_device)
     -> *mut libinput_device;
    pub fn libinput_device_unref(device: *mut libinput_device)
     -> *mut libinput_device;
    pub fn libinput_device_set_user_data(device: *mut libinput_device,
                                         user_data:
                                             *mut ::std::os::raw::c_void);
    pub fn libinput_device_get_user_data(device: *mut libinput_device)
     -> *mut ::std::os::raw::c_void;
    pub fn libinput_device_get_context(device: *mut libinput_device)
     -> *mut libinput;
    pub fn libinput_device_get_device_group(device: *mut libinput_device)
     -> *mut libinput_device_group;
    pub fn libinput_device_get_sysname(device: *mut libinput_device)
     -> *const ::std::os::raw::c_char;
    pub fn libinput_device_get_name(device: *mut libinput_device)
     -> *const ::std::os::raw::c_char;
    pub fn libinput_device_get_id_product(device: *mut libinput_device)
     -> ::std::os::raw::c_uint;
    pub fn libinput_device_get_id_vendor(device: *mut libinput_device)
     -> ::std::os::raw::c_uint;
    pub fn libinput_device_get_output_name(device: *mut libinput_device)
     -> *const ::std::os::raw::c_char;
    pub fn libinput_device_get_seat(device: *mut libinput_device)
     -> *mut libinput_seat;
    pub fn libinput_device_set_seat_logical_name(device: *mut libinput_device,
                                                 name:
                                                     *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_get_udev_device(device: *mut libinput_device)
     -> *mut udev_device;
    pub fn libinput_device_led_update(device: *mut libinput_device,
                                      leds: libinput_led);
    pub fn libinput_device_has_capability(device: *mut libinput_device,
                                          capability:
                                              libinput_device_capability)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_get_size(device: *mut libinput_device,
                                    width: *mut f64, height: *mut f64)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_pointer_has_button(device: *mut libinput_device,
                                              code: uint32_t)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_keyboard_has_key(device: *mut libinput_device,
                                            code: uint32_t)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_tablet_pad_get_num_buttons(device:
                                                          *mut libinput_device)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_tablet_pad_get_num_rings(device:
                                                        *mut libinput_device)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_tablet_pad_get_num_strips(device:
                                                         *mut libinput_device)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_group_ref(group: *mut libinput_device_group)
     -> *mut libinput_device_group;
    pub fn libinput_device_group_unref(group: *mut libinput_device_group)
     -> *mut libinput_device_group;
    pub fn libinput_device_group_set_user_data(group:
                                                   *mut libinput_device_group,
                                               user_data:
                                                   *mut ::std::os::raw::c_void);
    pub fn libinput_device_group_get_user_data(group:
                                                   *mut libinput_device_group)
     -> *mut ::std::os::raw::c_void;
    pub fn libinput_config_status_to_str(status: libinput_config_status)
     -> *const ::std::os::raw::c_char;
    pub fn libinput_device_config_tap_get_finger_count(device:
                                                           *mut libinput_device)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_config_tap_set_enabled(device:
                                                      *mut libinput_device,
                                                  enable:
                                                      libinput_config_tap_state)
     -> libinput_config_status;
    pub fn libinput_device_config_tap_get_enabled(device:
                                                      *mut libinput_device)
     -> libinput_config_tap_state;
    pub fn libinput_device_config_tap_get_default_enabled(device:
                                                              *mut libinput_device)
     -> libinput_config_tap_state;
    pub fn libinput_device_config_tap_set_button_map(device:
                                                         *mut libinput_device,
                                                     map:
                                                         libinput_config_tap_button_map)
     -> libinput_config_status;
    pub fn libinput_device_config_tap_get_button_map(device:
                                                         *mut libinput_device)
     -> libinput_config_tap_button_map;
    pub fn libinput_device_config_tap_get_default_button_map(device:
                                                                 *mut libinput_device)
     -> libinput_config_tap_button_map;
    pub fn libinput_device_config_tap_set_drag_enabled(device:
                                                           *mut libinput_device,
                                                       enable:
                                                           libinput_config_drag_state)
     -> libinput_config_status;
    pub fn libinput_device_config_tap_get_drag_enabled(device:
                                                           *mut libinput_device)
     -> libinput_config_drag_state;
    pub fn libinput_device_config_tap_get_default_drag_enabled(device:
                                                                   *mut libinput_device)
     -> libinput_config_drag_state;
    pub fn libinput_device_config_tap_set_drag_lock_enabled(device:
                                                                *mut libinput_device,
                                                            enable:
                                                                libinput_config_drag_lock_state)
     -> libinput_config_status;
    pub fn libinput_device_config_tap_get_drag_lock_enabled(device:
                                                                *mut libinput_device)
     -> libinput_config_drag_lock_state;
    pub fn libinput_device_config_tap_get_default_drag_lock_enabled(device:
                                                                        *mut libinput_device)
     -> libinput_config_drag_lock_state;
    pub fn libinput_device_config_calibration_has_matrix(device:
                                                             *mut libinput_device)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_config_calibration_set_matrix(device:
                                                             *mut libinput_device,
                                                         matrix: *mut f32)
     -> libinput_config_status;
    pub fn libinput_device_config_calibration_get_matrix(device:
                                                             *mut libinput_device,
                                                         matrix: *mut f32)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_config_calibration_get_default_matrix(device:
                                                                     *mut libinput_device,
                                                                 matrix:
                                                                     *mut f32)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_config_send_events_get_modes(device:
                                                            *mut libinput_device)
     -> uint32_t;
    pub fn libinput_device_config_send_events_set_mode(device:
                                                           *mut libinput_device,
                                                       mode: uint32_t)
     -> libinput_config_status;
    pub fn libinput_device_config_send_events_get_mode(device:
                                                           *mut libinput_device)
     -> uint32_t;
    pub fn libinput_device_config_send_events_get_default_mode(device:
                                                                   *mut libinput_device)
     -> uint32_t;
    pub fn libinput_device_config_accel_is_available(device:
                                                         *mut libinput_device)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_config_accel_set_speed(device:
                                                      *mut libinput_device,
                                                  speed: f64)
     -> libinput_config_status;
    pub fn libinput_device_config_accel_get_speed(device:
                                                      *mut libinput_device)
     -> f64;
    pub fn libinput_device_config_accel_get_default_speed(device:
                                                              *mut libinput_device)
     -> f64;
    pub fn libinput_device_config_accel_get_profiles(device:
                                                         *mut libinput_device)
     -> uint32_t;
    pub fn libinput_device_config_accel_set_profile(device:
                                                        *mut libinput_device,
                                                    mode:
                                                        libinput_config_accel_profile)
     -> libinput_config_status;
    pub fn libinput_device_config_accel_get_profile(device:
                                                        *mut libinput_device)
     -> libinput_config_accel_profile;
    pub fn libinput_device_config_accel_get_default_profile(device:
                                                                *mut libinput_device)
     -> libinput_config_accel_profile;
    pub fn libinput_device_config_scroll_has_natural_scroll(device:
                                                                *mut libinput_device)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_config_scroll_set_natural_scroll_enabled(device:
                                                                        *mut libinput_device,
                                                                    enable:
                                                                        ::std::os::raw::c_int)
     -> libinput_config_status;
    pub fn libinput_device_config_scroll_get_natural_scroll_enabled(device:
                                                                        *mut libinput_device)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_config_scroll_get_default_natural_scroll_enabled(device:
                                                                                *mut libinput_device)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_config_left_handed_is_available(device:
                                                               *mut libinput_device)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_config_left_handed_set(device:
                                                      *mut libinput_device,
                                                  left_handed:
                                                      ::std::os::raw::c_int)
     -> libinput_config_status;
    pub fn libinput_device_config_left_handed_get(device:
                                                      *mut libinput_device)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_config_left_handed_get_default(device:
                                                              *mut libinput_device)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_config_click_get_methods(device:
                                                        *mut libinput_device)
     -> uint32_t;
    pub fn libinput_device_config_click_set_method(device:
                                                       *mut libinput_device,
                                                   method:
                                                       libinput_config_click_method)
     -> libinput_config_status;
    pub fn libinput_device_config_click_get_method(device:
                                                       *mut libinput_device)
     -> libinput_config_click_method;
    pub fn libinput_device_config_click_get_default_method(device:
                                                               *mut libinput_device)
     -> libinput_config_click_method;
    pub fn libinput_device_config_middle_emulation_is_available(device:
                                                                    *mut libinput_device)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_config_middle_emulation_set_enabled(device:
                                                                   *mut libinput_device,
                                                               enable:
                                                                   libinput_config_middle_emulation_state)
     -> libinput_config_status;
    pub fn libinput_device_config_middle_emulation_get_enabled(device:
                                                                   *mut libinput_device)
     -> libinput_config_middle_emulation_state;
    pub fn libinput_device_config_middle_emulation_get_default_enabled(device:
                                                                           *mut libinput_device)
     -> libinput_config_middle_emulation_state;
    pub fn libinput_device_config_scroll_get_methods(device:
                                                         *mut libinput_device)
     -> uint32_t;
    pub fn libinput_device_config_scroll_set_method(device:
                                                        *mut libinput_device,
                                                    method:
                                                        libinput_config_scroll_method)
     -> libinput_config_status;
    pub fn libinput_device_config_scroll_get_method(device:
                                                        *mut libinput_device)
     -> libinput_config_scroll_method;
    pub fn libinput_device_config_scroll_get_default_method(device:
                                                                *mut libinput_device)
     -> libinput_config_scroll_method;
    pub fn libinput_device_config_scroll_set_button(device:
                                                        *mut libinput_device,
                                                    button: uint32_t)
     -> libinput_config_status;
    pub fn libinput_device_config_scroll_get_button(device:
                                                        *mut libinput_device)
     -> uint32_t;
    pub fn libinput_device_config_scroll_get_default_button(device:
                                                                *mut libinput_device)
     -> uint32_t;
    pub fn libinput_device_config_dwt_is_available(device:
                                                       *mut libinput_device)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_config_dwt_set_enabled(device:
                                                      *mut libinput_device,
                                                  enable:
                                                      libinput_config_dwt_state)
     -> libinput_config_status;
    pub fn libinput_device_config_dwt_get_enabled(device:
                                                      *mut libinput_device)
     -> libinput_config_dwt_state;
    pub fn libinput_device_config_dwt_get_default_enabled(device:
                                                              *mut libinput_device)
     -> libinput_config_dwt_state;
    pub fn libinput_device_config_rotation_is_available(device:
                                                            *mut libinput_device)
     -> ::std::os::raw::c_int;
    pub fn libinput_device_config_rotation_set_angle(device:
                                                         *mut libinput_device,
                                                     degrees_cw:
                                                         ::std::os::raw::c_uint)
     -> libinput_config_status;
    pub fn libinput_device_config_rotation_get_angle(device:
                                                         *mut libinput_device)
     -> ::std::os::raw::c_uint;
    pub fn libinput_device_config_rotation_get_default_angle(device:
                                                                 *mut libinput_device)
     -> ::std::os::raw::c_uint;
}
